name: "Check if PR is out-of-date"
on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is behind
        run: |
          commits_behind="$(gh api /repos/OWNER/REPO/compare/BASEHEAD --jq .behind_by)"
          echo 'COMMITS_BEHIND='$commits_behind >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          BASE: ${{ github.base_ref }}
          HEAD: ${{ github.head_ref }}
          BASEHEAD: "BASE...HEAD"
        run: echo "This PR is $COMMITS_BEHIND commits behind the target branch"
