name: Bump 'n' release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      REPO=${{ github.repository }}
    steps:
      - name: Get latest release tag # can also be draft release
        run: |
          LATEST_TAG=$(gh -R $REPO release list -L 1 |awk '{printf $3}')
          echo "Latest version tag for releases in $REPO is $LATEST_TAG"

      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Current version
        run: |
          CURRENT_VERSION=$(cat padd.sh | grep '^padd_version=' | cut -d'"' -f 2)
          echo "Current PADD version is $CURRENT_VERSION"
